CREATE TABLE RUN_LOG (
ID INT NOT NULL AUTO_INCREMENT,
SCRIPT TEXT,
ANCHOR_CITY_ID INT,
RUN_TIME DATETIME,
RECORDS_INSERTED INT,
RECORDS_SKIPPED INT,
PRIMARY KEY(ID)
);

CREATE TABLE REGIONS (
REG_ID INT NOT NULL AUTO_INCREMENT,
REGION TEXT,
PRIMARY KEY(REG_ID)
);

INSERT INTO REGIONS (REGION)
VALUES ('NORTHEAST'),
('MIDWEST'),
('WEST'),
('SOUTH');

CREATE TABLE DIVISIONS (
DIV_ID INT NOT NULL AUTO_INCREMENT,
DIVISION TEXT,
REG_ID INT,
FOREIGN KEY(REG_ID) REFERENCES REGIONS(REG_ID) ON DELETE CASCADE,
PRIMARY KEY(DIV_ID)
);

INSERT INTO DIVISIONS (DIVISION, REG_ID)
VALUES ('NEW ENGLAND', (SELECT REG_ID FROM REGIONS WHERE REGION = 'NORTHEAST')),
('MIDDLE ATLANTIC', (SELECT REG_ID FROM REGIONS WHERE REGION = 'NORTHEAST')),
('EAST NORTH CENTRAL', (SELECT REG_ID FROM REGIONS WHERE REGION = 'MIDWEST')),
('WEST NORTH CENTRAL', (SELECT REG_ID FROM REGIONS WHERE REGION = 'MIDWEST')),
('MOUNTAIN', (SELECT REG_ID FROM REGIONS WHERE REGION = 'WEST')),
('PACIFIC', (SELECT REG_ID FROM REGIONS WHERE REGION = 'WEST')),
('SOUTH ATLANTIC', (SELECT REG_ID FROM REGIONS WHERE REGION = 'SOUTH')),
('EAST SOUTH CENTRAL', (SELECT REG_ID FROM REGIONS WHERE REGION = 'SOUTH')),
('WEST SOUTH CENTRAL', (SELECT REG_ID FROM REGIONS WHERE REGION = 'SOUTH'));

CREATE TABLE STATES (
STATE_ID INT NOT NULL AUTO_INCREMENT,
STATE TEXT,
STATE_ABBR TEXT,
DIV_ID INT, 
FOREIGN KEY(DIV_ID) REFERENCES DIVISIONS(DIV_ID) ON DELETE CASCADE,
PRIMARY KEY(STATE_ID)
);

INSERT INTO STATES (STATE_ABBR,STATE,DIV_ID) 
VALUES ('AL','ALABAMA', (SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'EAST SOUTH CENTRAL')),
('AK','ALASKA',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'PACIFIC')),
('AZ','ARIZONA',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'MOUNTAIN')),
('AR','ARKANSAS',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'WEST SOUTH CENTRAL')),
('CA','CALIFORNIA',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'PACIFIC')),
('CO','COLORADO',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'MOUNTAIN')),
('CT','CONNECTICUT',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'NEW ENGLAND')),
('DE','DELAWARE',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'SOUTH ATLANTIC')),
('FL','FLORIDA',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'SOUTH ATLANTIC')),
('GA','GEORGIA',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'SOUTH ATLANTIC')),
('HI','HAWAII',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'PACIFIC')),
('ID','IDAHO',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'MOUNTAIN')),
('IL','ILLINOIS',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'EAST NORTH CENTRAL')),
('IN','INDIANA',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'EAST NORTH CENTRAL')),
('IA','IOWA',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'WEST NORTH CENTRAL')),
('KS','KANSAS',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'WEST NORTH CENTRAL')),
('KY','KENTUCKY',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'EAST SOUTH CENTRAL')),
('LA','LOUISIANA',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'WEST SOUTH CENTRAL')),
('ME','MAINE',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'NEW ENGLAND')),
('MD','MARYLAND',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'SOUTH ATLANTIC')),
('MA','MASSACHUSETTS',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'NEW ENGLAND')),
('MI','MICHIGAN',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'EAST NORTH CENTRAL')),
('MN','MINNESOTA',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'WEST NORTH CENTRAL')),
('MS','MISSISSIPPI',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'EAST SOUTH CENTRAL')),
('MO','MISSOURI',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'WEST NORTH CENTRAL')),
('MT','MONTANA',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'MOUNTAIN')),
('NE','NEBRASKA',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'WEST NORTH CENTRAL')),
('NV','NEVADA',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'MOUNTAIN')),
('NH','NEW HAMPSHIRE',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'NEW ENGLAND')),
('NJ','NEW JERSEY',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'MIDDLE ATLANTIC')),
('NM','NEW MEXICO',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'MOUNTAIN')),
('NY','NEW YORK',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'MIDDLE ATLANTIC')),
('NC','NORTH CAROLINA',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'SOUTH ATLANTIC')),
('ND','NORTH DAKOTA',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'WEST NORTH CENTRAL')),
('OH','OHIO',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'EAST NORTH CENTRAL')),
('OK','OKLAHOMA',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'WEST SOUTH CENTRAL')),
('OR','OREGON',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'PACIFIC')),
('PA','PENNSYLVANIA',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'MIDDLE ATLANTIC')),
('RI','RHODE ISLAND',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'NEW ENGLAND')),
('SC','SOUTH CAROLINA',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'SOUTH ATLANTIC')),
('SD','SOUTH DAKOTA',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'WEST NORTH CENTRAL')),
('TN','TENNESSEE',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'EAST SOUTH CENTRAL')),
('TX','TEXAS',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'WEST SOUTH CENTRAL')),
('UT','UTAH',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'MOUNTAIN')),
('VT','VERMONT',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'NEW ENGLAND')),
('VA','VIRGINIA',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'SOUTH ATLANTIC')),
('WA','WASHINGTON',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'PACIFIC')),
('WV','WEST VIRGINIA',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'SOUTH ATLANTIC')),
('WI','WISCONSIN',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'EAST NORTH CENTRAL')),
('WY','WYOMING',(SELECT DIV_ID FROM DIVISIONS WHERE DIVISION = 'MOUNTAIN'));

CREATE TABLE CITIES (
CITY TEXT,
CITY_ASCII TEXT,
LAT FLOAT4,
LNG FLOAT4,
COUNTRY TEXT,
ISO2 TEXT,
ISO3 TEXT,
STATE_PROVINCE TEXT,
CAPTIAL TEXT,
POPULATION FLOAT,
CITY_ID INT NOT NULL, 
STATE_ID INT,
PRIMARY KEY (CITY_ID)
);

CREATE TABLE RUN_LOG (
RUN_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
LOAD_TYPE TEXT,
COMMENT TEXT,
FILEPATH TEXT)


CREATE TABLE EVENTS (
EVENT_ID INT NOT NULL AUTO_INCREMENT,
EVENT_NAME TEXT,
PRIMARY KEY(EVENT_ID)
);

ALTER TABLE EVENTS AUTO_INCREMENT = 3000;

INSERT INTO EVENTS (EVENT_NAME)
VALUES('EBOLA OUTBREAK'),
('TRUMP ELECTION'),
('SANDY HOOK'),
('SAME SEX MARRIAGE'),
('TRUMP IMPEACHMENT');


CREATE TABLE CAT_NAME (
NAME_ID INT NOT NULL AUTO_INCREMENT,
NAME_TEXT TEXT,
PRIMARY KEY (NAME_ID)
);

ALTER TABLE CAT_NAME AUTO_INCREMENT = 7000;

INSERT INTO CAT_NAME (NAME_TEXT)
VALUES ('CIVIL RIGHTS'),
('HELATH'),
('POLITICS'),
('WORLD');

CREATE TABLE CATEGORY(
CATEGORY_ID INT NOT NULL AUTO_INCREMENT,
EVENT_ID INT,
CAT_NAME_ID INT, 
FOREIGN KEY (EVENT_ID) REFERENCES EVENTS(EVENT_ID) ON DELETE CASCADE,
FOREIGN KEY (CAT_NAME_ID) REFERENCES CAT_NAME(NAME_ID) ON DELETE CASCADE,
PRIMARY KEY (CATEGORY_ID)
);

ALTER TABLE CATEGORY AUTO_INCREMENT = 4000;

INSERT INTO CATEGORY (EVENT_ID, CAT_NAME_ID)
VALUES(3000, 7000),
(3000, 7001),
(3000, 7003),
(3001, 7000),
(3001, 7002),
(3001, 7003),
(3002, 7000),
(3002, 7002),
(3003, 7000),
(3003, 7001),
(3003, 7002),
(3004, 7000),
(3004, 7002),
(3004, 7003);


CREATE TABLE SEARCH_DATES (
SEARCH_DATE_ID INT NOT NULL AUTO_INCREMENT,
SEARCH_START DATE,
SEARCH_END DATE,
PRIMARY KEY(SEARCH_DATE_ID)
);

ALTER TABLE SEARCH_DATES auto_increment=1000;

INSERT INTO SEARCH_DATES (SEARCH_START, SEARCH_END)
VALUES('2014-03-23', '2014-03-04');


CREATE TABLE SEARCHES(
SEARCH_ID INT NOT NULL AUTO_INCREMENT,
KEYWORD TEXT,
SEARCH_DATE_ID INT,
EVENT_ID INT,
FOREIGN KEY (SEARCH_DATE_ID) REFERENCES SEARCH_DATES(SEARCH_DATE_ID) ON DELETE CASCADE,
FOREIGN KEY (EVENT_ID) REFERENCES EVENTS(EVENT_ID) ON DELETE CASCADE,
PRIMARY KEY (SEARCH_ID)
);

ALTER TABLE SEARCHES AUTO_INCREMENT = 2000;

CREATE TABLE USERS (
AUTHOR_ID VARCHAR(50) NOT NULL,
CREATED_AT DATE,
LOCATION TEXT,
DESCRIPTION TEXT,
FOLLOWERS_COUNT INT,
FOLLOWING_COUNT INT,
LISTED_COUNT INT,
TWEET_COUNT INT,
VERIFIED TEXT,
PRIMARY KEY(AUTHOR_ID)
);

CREATE TABLE TWEET_TEXT (
TWEET_ID VARCHAR(50) NOT NULL,
TWEET TEXT,
PRIMARY KEY (TWEET_ID)
);

CREATE TABLE TWEET_DATA (
DATA_ID INT NOT NULL AUTO_INCREMENT,
AUTHOR_ID VARCHAR(50),
CREATED_AT DATE,
TWEET_ID VARCHAR(50), 
SEARCH_ID INT,
FOREIGN KEY (AUTHOR_ID) REFERENCES USERS(AUTHOR_ID) ON DELETE CASCADE,
FOREIGN KEY (TWEET_ID) REFERENCES TWEET_TEXT(TWEET_ID) ON DELETE CASCADE,
FOREIGN KEY (SEARCH_ID) REFERENCES SEARCHES(SEARCH_ID) ON DELETE CASCADE,
PRIMARY KEY (DATA_ID)
);

ALTER TABLE TWEET_DATA AUTO_INCREMENT = 5000;

CREATE TABLE WORD_ASSOCIATION (
WA_ID INT NOT NULL AUTO_INCREMENT,
TWEET_ID VARCHAR(50),
TERM TEXT,
EMOTION TEXT,
FOREIGN KEY (TWEET_ID) REFERENCES TWEET_DATA(TWEET_ID) ON DELETE CASCADE,
PRIMARY KEY (WA_ID)
);

ALTER TABLE WORD_ASSOCIATION AUTO_INCREMENT = 8000;

CREATE TABLE SENTIMENT_CATEGORY (
SENT_ID INT,
SENTIMENT_CATEGORY VARCHAR(50),
PRIMARY KEY(SENT_ID)
);

INSERT INTO SENTIMENT_CATEGORY (SENT_ID, SENTIMENT_CATEGORY)
VALUES(1, 'POSITIVE'),
(0, 'NEGATIVE'),
(9, 'NEUTRAL');

CREATE TABLE SENTIMENT_CATEGORY_ASSIGMENT(
TWEET_ID VARCHAR(50),
SENT_ID INT,
FOREIGN KEY (SENT_ID) REFERENCES SENTIMENT_CATEGORY(SENT_ID) ON DELETE CASCADE,
FOREIGN KEY (TWEET_ID) REFERENCES TWEET_DATA(TWEET_ID) ON DELETE CASCADE,
PRIMARY KEY(TWEET_ID));

CREATE TABLE AUTHOR_LOCATION(
AUTHOR_ID VARCHAR(50),
STATE_ID INT,
FOREIGN KEY (AUTHOR_ID) REFERENCES TWEET_DATA(AUTHOR_ID) ON DELETE CASCADE,
FOREIGN KEY (STATE_ID) REFERENCES US_STATES(STATE_ID) ON DELETE CASCADE,
PRIMARY KEY(AUTHOR_ID)
);

----------------View Creation--------------------------
CREATE VIEW `VW_US_CITIES` AS
    SELECT 
        `CITIES`.`CITY` AS `CITY`,
        `CITIES`.`CITY_ASCII` AS `CITY_ASCII`,
        `CITIES`.`LAT` AS `LAT`,
        `CITIES`.`LNG` AS `LNG`,
        `CITIES`.`COUNTRY` AS `COUNTRY`,
        `CITIES`.`ISO2` AS `ISO2`,
        `CITIES`.`ISO3` AS `ISO3`,
        `CITIES`.`STATE_PROVINCE` AS `STATE_PROVINCE`,
        `CITIES`.`CAPTIAL` AS `CAPTIAL`,
        `CITIES`.`POPULATION` AS `POPULATION`,
        `CITIES`.`CITY_ID` AS `CITY_ID`,
        `CITIES`.`STATE_ID` AS `STATE_ID`
    FROM
        `CITIES`
    WHERE
        (`CITIES`.`STATE_ID` <> 0)

CREATE 
VIEW `VW_US_CITIES` AS
    SELECT 
        `CITIES`.`CITY` AS `CITY`,
        `CITIES`.`CITY_ASCII` AS `CITY_ASCII`,
        `CITIES`.`LAT` AS `LAT`,
        `CITIES`.`LNG` AS `LNG`,
        `CITIES`.`COUNTRY` AS `COUNTRY`,
        `CITIES`.`ISO2` AS `ISO2`,
        `CITIES`.`ISO3` AS `ISO3`,
        `CITIES`.`STATE_PROVINCE` AS `STATE_PROVINCE`,
        `CITIES`.`CAPTIAL` AS `CAPTIAL`,
        `CITIES`.`POPULATION` AS `POPULATION`,
        `CITIES`.`CITY_ID` AS `CITY_ID`,
        `CITIES`.`STATE_ID` AS `STATE_ID`
    FROM
        `CITIES`
    WHERE
        (`CITIES`.`STATE_ID` <> 0)

CREATE 
VIEW `VW_CAT_EVENTS` AS
    SELECT 
        `C`.`CATEGORY_ID` AS `CATEGORY_ID`,
        `C`.`EVENT_ID` AS `EVENT_ID`,
        GROUP_CONCAT(`CN`.`NAME_TEXT`
            SEPARATOR ', ') AS `CATEGORIES`,
        `E`.`EVENT_NAME` AS `EVENT_NAME`
    FROM
        ((`CATEGORY` `C`
        JOIN `CAT_NAME` `CN` ON ((`C`.`CAT_NAME_ID` = `CN`.`NAME_ID`)))
        JOIN `EVENTS` `E` ON ((`E`.`EVENT_ID` = `C`.`EVENT_ID`)))
    GROUP BY `C`.`EVENT_ID`

CREATE 
VIEW `VW_TWEET_TEXT` AS
    SELECT 
        `TWEET_TEXT`.`TWEET_ID` AS `TWEET_ID`,
        (CASE
            WHEN
                ((`TWEET_TEXT`.`RETWEET_ID` IS NOT NULL)
                    AND (`TWEET_TEXT`.`TWEET` LIKE 'RT%'))
            THEN
                `TWEET_TEXT`.`RETWEET_TEXT`
            ELSE `TWEET_TEXT`.`TWEET`
        END) AS `TWEET_TEXT`
    FROM
        `TWEET_TEXT`

CREATE 
VIEW `VW_TWEETS` AS
    SELECT 
        `TD`.`AUTHOR_ID` AS `AUTHOR_ID`,
        `TD`.`CREATED_AT` AS `TWEET_CREATED`,
        `TD`.`TWEET_ID` AS `TWEET_ID`,
        `S`.`KEYWORD` AS `KEYWORD_SEARCH`,
        `CE`.`CATEGORIES` AS `CATEGORIES`,
        `CE`.`EVENT_NAME` AS `EVENT_NAME`,
        `TT`.`TWEET_TEXT` AS `TWEET_TEXT`
    FROM
        (((`TWEET_DATA` `TD`
        JOIN `SEARCHES` `S` ON ((`S`.`SEARCH_ID` = `TD`.`SEARCH_ID`)))
        JOIN `VW_CAT_EVENTS` `CE` ON ((`CE`.`EVENT_ID` = `S`.`EVENT_ID`)))
        JOIN `VW_TWEET_TEXT` `TT` ON ((`TD`.`TWEET_ID` = `TT`.`TWEET_ID`)))

CREATE 
VIEW `VW_US_CITIES` AS
    SELECT 
        `CITIES`.`CITY` AS `CITY`,
        `CITIES`.`CITY_ASCII` AS `CITY_ASCII`,
        `CITIES`.`LAT` AS `LAT`,
        `CITIES`.`LNG` AS `LNG`,
        `CITIES`.`COUNTRY` AS `COUNTRY`,
        `CITIES`.`ISO2` AS `ISO2`,
        `CITIES`.`ISO3` AS `ISO3`,
        `CITIES`.`STATE_PROVINCE` AS `STATE_PROVINCE`,
        `CITIES`.`CAPTIAL` AS `CAPTIAL`,
        `CITIES`.`POPULATION` AS `POPULATION`,
        `CITIES`.`CITY_ID` AS `CITY_ID`,
        `CITIES`.`STATE_ID` AS `STATE_ID`
    FROM
        `CITIES`
    WHERE
        (`CITIES`.`STATE_ID` <> 0)
---From data load, the following records need correction
UPDATE CITIES
SET STATE_ID = 0
WHERE CITY_ID IN (
1100440040
,1100553391
,1100932516
,1100946651
,1430540258
);
